services:
  web:
    build: .
    image: kevin-daily-web:latest
    container_name: kevin-daily-web
    ports:
      - "3000:3000"
    environment:
      - VITE_PB_URL=http://192.168.31.10:8091
    restart: unless-stopped
    network_mode: host
